### ISSUE TITLE
Failed Installation (invalid syntax)

### ISSUE THREAD

**Issue by nimamox** [lucfra/ExperimentManager#1]
I'm trying to use the far-ho package that has ExperimentManagement as its dependency. But after installation I get an "invalid syntax" error!

```
$ pip install git+git://github.com/lucfra/FAR-HO.git

$ python -c "import far_ho"
Warning:
No module named experiment_manager.utils
This is not a required package! However, there might be a couple of functions which could be helpful there!
Might get it at https://github.com/lucfra/ExperimentManager
ordered-set package not found..

$ pip install git+git://github.com/lucfra/ExperimentManager.git

$ python -c "import far_ho"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/far_ho/__init__.py", line 1, in <module>
    from far_ho.hyper_parameters import *
  File "/usr/local/lib/python2.7/site-packages/far_ho/hyper_parameters.py", line 11, in <module>
    from far_ho.utils import maybe_call, maybe_eval, merge_dicts, as_list
  File "/usr/local/lib/python2.7/site-packages/far_ho/utils.py", line 8, in <module>
    from experiment_manager.utils import *
  File "/usr/local/lib/python2.7/site-packages/experiment_manager/__init__.py", line 1, in <module>
    from experiment_manager.datasets.structures import *
  File "/usr/local/lib/python2.7/site-packages/experiment_manager/datasets/structures.py", line 207
    return {**{x: self.data, y: self.target}, **other_feeds}
             ^
SyntaxError: invalid syntax
```

**Comment by AmirooR** [comment]
@nimamox  Try using python3.

**Comment by lucfra** [comment]
Yes is because you are using Python 2.

Cheers, 

Luca

**Comment by nimamox** [comment]
Thanks the problem is solved.
